version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - '${CONFIG}/database:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dozer']
      interval: 5s
      timeout: 5s
      retries: 5

  dozer:
    image: dozer:latest
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - '${CONFIG}/config:/app/config'

  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - './docs/_build/html:/usr/share/nginx/html:ro'
